apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello #서비스랑 연결할때 서비스의 selector와 같으면 연결됨.
spec:
  containers:
  - name: hello-container
    image: kubetm/hello # 도커 이미지 이름
    ports:
    - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector:
    app: hello  #pod의 labels안에 app과 같으면 됨.
  ports:
    - port: 8200 #외부에서 8200으로 접근하면
      targetPort: 8000 #pod의 8000번으로 간다.
  externalIPs:
  - 192.168.123.106 
  # k3s가 설치된 컴퓨터의 ip를 써줘야함. 
  # 위에서 노출한 포트로 접속하면 외부에서 접근가능해짐.