apiVersion: v1
kind: Pod
metadata:
  name: test-1
  labels:
    type: web
    lo: dev
spec:
  containers:
  - name: container
    image: kubetm/hello

  # nodeSelector:
  #   disktype: ssd
---

apiVersion: v1
kind: Service
metadata:
  name: test-1
spec:
  selector:
    type: web
  ports:
  - port: 8000
